version: '2'

services:
    mysnips:
        restart: always
        container_name: mysnips
        build: mysnips
        privileged: true
        ports:
            - "9898:1883"
            - "5043:22"
        expose:
            - "5043"
        volumes:
            - /dev/snd:/dev/snd
            - ./assistant:/usr/share/snips/assistant
            - ./snips.toml:/etc/snips.toml
            - /etc/asound.conf:/etc/asound.conf
            - ~/.config/pulse/cookie:/root/.config/pulse/cookie
            - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
        environment:
            - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
            - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
        group_add:
            - 995
